### ISSUE TITLE
Add dark mode option

### ISSUE THREAD

**Issue by aminah-io** [mdn/kuma#6880] opened 2020-04-15 23:37 UTC
**Summary**
_What problem would this solve?_
Adding dark mode, which would make it easier on the eyes.

**Audience**
_Who has this problem? Everyone? Article authors? Etc._
People with sensitive eyes who love reading MDN documentation.

**Rationale**
_How do you know that people identified above actually have this problem?_
Most people with sensitive eyes usually have a hard time with websites that bright color backgrounds, such as white.

**Workaround**
_How are the people identified above currently handling this problem?_
Dimming their screens, but this can be an issue for people with eyesight issues.

**Proposal**
_Do you have suggestions for solving this problem?_
Some ReactJS UI frameworks have dark mode built in. It looks like MDN uses React. I'd suggest possibly using a ReactJS UI framework to easily give users the option to use dark mode if they need it.

**Additional context**
_Is there anything else we should know?_
I love MDN 🥺 this would make my eyes, and I'm sure the eyes of others, very happy. Please and thank you.

**Comment by tobinmori** [comment] 2020-04-27 16:14
Thanks for suggesting this Aminah, we have a similar issue for this already, so closing this one.

**Comment by peterbe** [comment] 2020-05-01 16:09
@tobinmori Because we don't know where that issue is, I think we should use this ( @aminah-io 's ) issue as the issue for this. Perhaps it was once in Bugzilla. Or, perhaps it's in Fiori or something.

**Comment by leonadler** [comment] 2021-08-12 05:29
This is the old issue from bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1427452

**Comment by reduckted** [comment] 2021-09-09 06:28
Following the latest link in that Bugzilla issue led me to the [mdn/yari](https://github.com/mdn/yari) repository, which contains the discussion https://github.com/mdn/yari/discussions/2539, which seems to have a bit more activity than this issue. 

A bunch of other issues about a dark theme across a variety of repos have been closed as a duplicate of that discussion, so maybe https://github.com/mdn/yari/discussions/2539 is the source or truth. 🤷‍♂️ 

Either way, my eyes would be very thankful for a dark theme. 😄

**Comment by escattone** [comment] 2021-09-09 16:51
@reduckted Yes, good catch, this issue doesn't make sense here any longer. Closing this, since mdn/yari#2539 is the new "source of truth" for this topic.

**Closed by escattone** 2021-09-09 16:51 UTC
Labels: p3
