### ISSUE TITLE
Hii, 🙄Please add "Dark Mode". Which will be helpful for all. Its makes us easy to study.🙂 

### ISSUE THREAD

**Issue by kiran-khanna** [mdn/kuma#7476] opened 2020-09-05 16:52 UTC
**Summary**
_What problem would this solve?_

**Audience**
_Who has this problem? Everyone? Article authors? Etc._

**Rationale**
_How do you know that people identified above actually have this problem?_

**Workaround**
_How are the people identified above currently handling this problem?_

**Proposal**
_Do you have suggestions for solving this problem?_

**Additional context**
_Is there anything else we should know?_

**Comment by peterbe** [comment] 2020-09-28 16:09
Dupe of https://github.com/mdn/kuma/issues/7285

**Closed by peterbe** 2020-09-28 16:09 UTC
Labels: status: needs triage
