### ISSUE TITLE
U - Move subscription management out of the wiki

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6703] opened 2020-03-19 15:33 UTC
**Summary**
Thanks to https://github.com/mdn/kuma/issues/6322 the Edit Profile page stays on the read-only site (no `wiki.` in the URL) and it uses the read-only site header & footer. 

However, /en-US/payments/recurring/management is still on the Wiki. 

**Acceptance Criteria**
- [x] subscription management page reactified
- [x] terms page reactified

**Rationale**
You don't want to, or should have to, see the Wiki (header or domain) if all you're doing is setting up and managing a subscription. 

**Audience**
Everyone

**Proposal**
Do whatever we do in https://github.com/mdn/kuma/issues/6322 to the `/$locale/payments/recurring/management` page. And other `/$locale/payments/*` pages such as the `terms` page. 

**Additional context**
Hmm

**Comment by mindy** [comment] 2020-04-06 18:38
@malqinneh Do you know where I can find the original design for this page? Wondering if there are any differences between what we currently have on production and the intended design. 

<img width="1316" alt="payment-management" src="https://user-images.githubusercontent.com/650/78593225-46291d00-7814-11ea-9c24-45c22925ebba.png">

**Comment by malqinneh** [comment] 2020-04-06 21:47
Spoke to Mindy, basically we grandfathered the current [MDN subscription management] page (screenshot above) as is, with all existing functionality/UI.

We have a few options if we want to optimize this experience. 1) *not* taking users to a separate page to manage their subscription.

**Comment by mindy** [comment] 2020-04-07 15:03
I think given the time constraints (this was slated to be done for Delta), I vote for option 2. 

I also wanted to clarify that I didn't want to take too much of your time, Mustafa! I thought there could be some small improvements that we could weasel in while working on the main task of this ticket.

**Comment by malqinneh** [comment] 2020-04-07 15:14
Of course! I think we can clean it up. Checked to see if we're currently using that page to manage any other membership type on MDN. The current copy makes it seem like we are. Want to make sure we don't remove relevant copy.

**Comment by peterbe** [comment] 2020-04-07 17:43
If we do bother to change the functionality (other than just moving it from the Wiki's jinja templates to React) the only functional thing I'd like to see is that we don't format the amount like "$0.0" :)
Which brings to mind; how the heck did you manage to set up a subscription of $0 @mindy ??

**Comment by malqinneh** [comment] 2020-04-07 18:07
<img width="885" alt="Screen Shot 2020-04-07 at 2 06 47 PM@mindy c="https://user-images.githubusercontent.com/4819906/78703926-0ed07400-78d9-11ea-8b20-704c96ca191a.png">

@mindy let me know if the above looks feasible (without adding too much work). Don't mind the styling too much, we can keep whatever style is in production.

**Comment by malqinneh** [comment] 2020-04-07 18:18
> If we do bother to change the functionality (other than just moving it from the Wiki's jinja templates to React) the only functional thing I'd like to see is that we don't format the amount like "$0.0" :)
> Which brings to mind; how the heck did you manage to set up a subscription of $0 @mindy ??

Grandfathered from the past experiment, there will be users who "subscribed" with $2 or $6. Confirmed with @atopal that we will leave all current subscription amounts as is.

**Comment by peterbe** [comment] 2020-04-07 18:38
Perhaps also replace the "Back to profile" with a link to the Subscription landing page?

**Comment by malqinneh** [comment] 2020-04-07 18:43
> Perhaps also replace the "Back to profile" with a link to the Subscription landing page?

The user would have come to this page from their user profile (think the initial UX provides a way for users to return back from where they came from).

Why would the user want to go to the subscription landing page at the point they are at?

**Comment by mindy** [comment] 2020-04-07 19:54
This looks so much better and feasible-- thanks Mustafa! 

> The user would have come to this page from their user profile (think the initial UX provides a way for users to return back from where they came from). 

☝️There are currently three ways to get to this page:
- Edit user profile, as you already know (https://wiki.developer.allizom.org/en-US/profiles/[user]/edit)
- Payments landing page, question 12 (https://developer.allizom.org/en-US/payments)
- Payments thank you page (https://developer.allizom.org/en-US/payments/thank-you)

**Comment by malqinneh** [comment] 2020-04-07 20:10
> There are currently three ways to get to this page:
> 
>     * Edit user profile, as you already know ([https://wiki.developer.allizom.org/en-US/profiles/[user]/edit](https://wiki.developer.allizom.org/en-US/profiles/%5Buser%5D/edit))
> 
>     * Payments landing page, question 12 (https://developer.allizom.org/en-US/payments)
> 
>     * Payments thank you page (https://developer.allizom.org/en-US/payments/thank-you)

Thank you for clarifying @mindy! Forgot about linking from [Payment landing] and [Thank you] page(s).

In that case, if we implement the changes I suggested, can we also remove the button that takes you back to [Profile]?

**Comment by mindy** [comment] 2020-04-07 20:22
> In that case, if we implement the changes I suggested, can we also remove the button that takes you back to [Profile]?

Sounds good to me! Thank you!

**Comment by mindy** [comment] 2020-04-15 15:20
@atopal @tobinmori  Any objections to changing the url from " /payments/recurring/management" to "/payments/management" to be consistent with the rest of the payments urls?

**Comment by atopal** [comment] 2020-04-15 15:31
No, that sounds good to me, @mindy

**Comment by peterbe** [comment] 2020-04-15 19:50
> Any objections to changing the url from " /payments/recurring/management" to "/payments/management" to be consistent with the rest of the payments urls?

Might still be a good idea to leave a 301 redirect behind in `kuma/payments/urls.py`

**Comment by peterbe** [comment] 2020-04-22 15:28
@tobinmori I un-assigned @mindy from this issues since it's a user story. Devs should be assigned to tasks.

**Comment by chinikes** [comment] 2020-05-01 15:06
@atopal, @peterbe , @mindy, @tobinmori - With all tasks done, is this user story good as done?

**Comment by peterbe** [comment] 2020-05-01 15:30
> With all tasks done, is this user story good as done?

I can never remember the correct protocol. But isn't a sprint demo first and them @atopal closes the user story?

**Comment by chinikes** [comment] 2020-05-01 15:33
No, the user story can always be reviewed and closed in the middle of the sprint. In the retro, we talked about reviewing the user stories earlier in the sprint for a faster feedback from the PO

**Comment by peterbe** [comment] 2020-05-01 16:04
So how about this, Mindy, Kadir, and myself meet up on Zoom and demo the features of it if Kadir is happy with it, he closes the user story. Plan? Invite?

**Comment by chinikes** [comment] 2020-05-01 16:13
Kadir should be able to review when he's around on Monday. Any process that works for the team is all good.

**Comment by atopal** [comment] 2020-05-04 12:13
That sounds good to me @peterbe I'm around after the bug triage today, does that work for you?

**Closed** 2020-05-06 16:14 UTC
Labels: Epic, p2
