### ISSUE TITLE
I set default language english in profile, but site's language always my local.

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/kuma#6550] opened 2020-02-21 11:05 UTC
@hzx commented on [Thu Feb 20 2020](https://github.com/mdn/sprints/issues/2837)

# Request type

- [ ] Show site in language I set in my profile. In addition even after selecting default language in popup.

# Details
I set default language english in profile, but site's language always my local.
<img width="1790" alt="Screen Shot 2020-02-21 at 02 34 40" src="https://user-images.githubusercontent.com/869203/74990065-45e6e500-5453-11ea-9e0d-015dcb6fa4f8.png">

<img width="1781" alt="Screen Shot 2020-02-21 at 02 35 22" src="https://user-images.githubusercontent.com/869203/74990066-4a130280-5453-11ea-8f05-76d781c4002b.png">

<img width="627" alt="Screen Shot 2020-02-21 at 02 40 17" src="https://user-images.githubusercontent.com/869203/74990160-8e9e9e00-5453-11ea-994f-132b3340c13e.png">

<img width="1792" alt="Screen Shot 2020-02-21 at 02 41 51" src="https://user-images.githubusercontent.com/869203/74990386-3caa4800-5454-11ea-940c-bc176e10f08a.png">

---

@chrisdavidmills commented on [Fri Feb 21 2020](https://github.com/mdn/sprints/issues/2837#issuecomment-589607478)

This is more of a platform issue, so I'll move this over to the kuma repo.

**Comment by atopal** [comment] 2020-02-21 13:06
This is a duplicate of mdn/yari#6981

**Comment by peterbe** [comment] 2020-02-21 13:58
> This is a duplicate of mdn/yari#6981

Are you sure?

What @hzx is experiencing is a JS crash. `TypeError: Cannot read property 'getCookie' of undefined`
It comes from this line: https://github.com/mdn/kuma/blob/79abfd35af504d1ea8c0f36e7cee20a96011b915/kuma/static/js/main.js#L103

What that means is that `window.mdn.utils` hasn't been set. The only way it can be set is if `build/js/wiki.js` gets downloaded AND executed. But that `build/js/wiki.js` is loaded ASYNC (which is almost always a bad idea and a technical debt in Kuma). 

EIther way, https://github.com/mdn/yari/issues/6981 is most definitely about something else. I.e. if set that you prefer English but still stumbles on (e.g. a Google search in Spain) a URL that *has* a non-en-US locale in the URL already.

**Comment by peterbe** [comment] 2020-02-21 14:07
Yeah, pretty sure the flaw is that `async` on the script. 

`window.mdn.utils` gets set in side `js/utils/utils.js` which is part of the [`build/js/wiki.js` bundle](https://github.com/mdn/kuma/blob/79abfd35af504d1ea8c0f36e7cee20a96011b915/kuma/settings/common.py#L993)
But that bundle is disjointed from the [`main`](https://github.com/mdn/kuma/blob/79abfd35af504d1ea8c0f36e7cee20a96011b915/kuma/settings/common.py#L845-L859) bundle. So it's flawed logically. 

It could very well be that the dead easiest solution is to remove [`{"async": True}`](https://github.com/mdn/kuma/blob/79abfd35af504d1ea8c0f36e7cee20a96011b915/kuma/settings/common.py#L1003) from that bundle. But it might still require someone to verify that the *order* is still right in the loading of the bundles. 
https://github.com/mdn/kuma/blob/79abfd35af504d1ea8c0f36e7cee20a96011b915/kuma/settings/common.py#L993

**Comment by atopal** [comment] 2020-02-21 14:15
Ah, thanks for checking Peter, I read the too quickly indeed.

**Closed** 2020-02-26 08:34 UTC
Labels: comp: frontend, p2
