### ISSUE TITLE
Please restore topic filtering

### ISSUE THREAD

**Issue by bussdriver** [mdn/kuma#6884] opened 2020-04-16 21:16 UTC
**Summary**
Topic filtering was **EXTREMELY** useful for my students and myself.

**Rationale**
Overly broad search results are handled by filtering.  **NOTE:** I instructed students to create multiple filter bookmarks which then in firefox can use a keyword and %s to create instantly targeted searches without the need to fool around with filter checkboxes!

**Idea**
Perhaps add the feature only as a URL option and provide a simple javascript form to generate the URL to bookmark? As long as the backend topic filter exists you hardly need to change the website!

**Comment by peterbe** [comment] 2020-04-17 16:41
Thanks @bussdriver for sharing your thoughts. 
Unfortunately it's already a duplicate of: https://github.com/mdn/kuma/issues/5754
and unfortunately we haven't had time to address that one. 

As a workaround you can use the WIki's search. E.g. https://wiki.developer.mozilla.org/en-US/search?q=web&topic=mathml

**Closed by peterbe** 2020-04-17 16:41 UTC
Labels: status: needs triage
