### ISSUE TITLE
Main navigation dropdowns render partially below table of contents.

### ISSUE THREAD

**Issue by eli-crow** [mdn/kuma#6948] opened 2020-04-25 15:02 UTC
**Summary**
Your dropdown menus in the main navigation overlap the table of contents in a strange way.

**Steps To Reproduce (STR)**
1. go to https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit
2. Hover over "Technologies" in the main navigation.

**Actual behavior**
The navigation dropdowns render partially below the table of contents.

**Expected behavior**
The navigation dropdowns render completely on top of the table of contents

**Additional context**
A minor annoyance

<img width="1592" alt="Screen Shot 2020-04-25 at 10 57 03 AM" src="https://user-images.githubusercontent.com/19712894/80283262-3e0e2000-86e4-11ea-8cbb-bdcd5cddb3b3.png">

**Comment by igorradovanov** [comment] 2020-04-26 17:50
It can be reproduced on a Windows machine as well.

The issue appears to be related to the incorrect `z-index` value on the element named `.document-toc ul`.

**Comment by peterbe** [comment] 2020-04-27 12:14
Thank you for filing! But it's a dupe of https://github.com/mdn/kuma/issues/6942 
We'll fix it as soon as we can.

**Closed by peterbe** 2020-04-27 12:14 UTC
Labels: status: needs triage
