### ISSUE TITLE
Some Text editor on MDN webpage is broken 

### ISSUE THREAD

**Issue by jjbully** [mdn/kuma#7381] opened 2020-07-29 02:02 UTC
**Summary**
_What is the problem?_
the text editor on some MDN page doesnt show properly on chrome

 
**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. open chrome
2. go to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce
 

**Actual behavior**
_What actually happened?_
![MDN](https://user-images.githubusercontent.com/43172408/88747950-73faee80-d182-11ea-884b-9c56507eb423.jpg)

**Expected behavior**
_What did you expect to happen?_

**Additional context**
_Is there anything else we should know?_

**Comment by tobinmori** [comment] 2020-08-03 16:05
Thank you, we already have an issue for this filed. 

Duplicate of #7322

**Closed by tobinmori** 2020-08-03 16:05 UTC
Labels: status: needs triage
