### ISSUE TITLE
E - Explore Yari 1 Mitigations: Previewing changes for editing

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#6644] opened 2020-02-19 13:19 UTC
# User story
As a ..., I want to ..., so I can ...

*Ideally, this is in the issue title, but if not, you can put it here. If so, delete this section.*

# Acceptance criteria

- [ ] This is something that can be verified to show that this user story is satisfied.

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.

**Comment by peterbe** [comment] 2020-03-05 19:15
What does "Mitigations" mean here? The second part, "Previewing changes for editing" sounds like a perfectly normal feature (request).

**Comment by tobinmori** [comment] 2020-07-10 14:38
Closing, because i think this is a duplicate of #815

**Closed by tobinmori** 2020-07-10 14:38 UTC
Labels: Epic
