### ISSUE TITLE
ISE when trying to submit a translation

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/kuma#6970] opened 2020-04-30 05:50 UTC
**Summary**
_What is the problem?_
Submitting a translation in Italian for https://wiki.developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Publishing_your_website$translate?tolocale=it fails and gives an ISE

**Steps To Reproduce (STR)**
1. Went to https://wiki.developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Publishing_your_website$translate?tolocale=it
2. Added / Changed a bunch of words
3. Clicked "Publish"

**Actual behavior**
An ISE / error 500 happened, preventing to save the work.

**Expected behavior**
The localization is save, no error, the reader is able to read a new document

**Additional context**

* First report here: https://discourse.mozilla.org/t/50-internal-server-error-while-saving/58804
* I was not able to reproduce this on another locale (pl) for this page

**Comment by peterbe** [comment] 2020-04-30 15:29
For those with access, I think it's this error: https://sentry.prod.mozaws.net/operations/mdn-prod/issues/7440553/?query=is:unresolved

**Comment by peterbe** [comment] 2020-04-30 15:31
Actually, I suspect this is a dupe of https://github.com/mdn/kuma/issues/6766
I have to re-read that one one more time to get my brain back into it.

**Comment by peterbe** [comment] 2020-04-30 16:26
In https://discourse.mozilla.org/t/50-internal-server-error-while-saving/58804/2 it was reported that the URL they tried was: https://wiki.developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Publishing_your_website%24translate?tolocale=it

What I think is happening is that there is already a translated attempt at slug `Learn/Getting_started_with_the_web/Pubblicare_il_tuo_sito`  (in locale `it`) that exists as a soft-delete. 

```
>>> Document.objects.get(slug='Learn/Getting_started_with_the_web/Pubblicare_il_tuo_sito')
Traceback (most recent call last):
...
kuma.wiki.models.Document.DoesNotExist: Document matching query does not exist.
>>> Document.deleted_objects.get(slug='Learn/Getting_started_with_the_web/Pubblicare_il_tuo_sito')
<Document: /it/docs/Learn/Getting_started_with_the_web/Pubblicare_il_tuo_sito (Pubblicare il tuo sito)>
```

So, this time it's the soft-deletes that are blocking based on the *parent*. 

**Actually**, now that I opened up the files and dug into the error I might as well just fix it even instead of waiting for the triage-train: https://github.com/mdn/kuma/pull/6973

**Closed** 2020-05-01 00:05 UTC
Labels: status: needs triage

**Comment by SphinxKnight** [comment] 2020-05-02 08:52
Thanks a lot for this swift fixing @peterbe / @escattone  :)
