### ISSUE TITLE
关于收藏

### ISSUE THREAD

**Issue by FYS397** [mdn/kuma#6188] opened 2019-12-04 03:05 UTC
子标题收藏按钮不见了

**Comment by callahad** [comment] 2019-12-09 17:34
(Google Translate)

> Subtitle favorite button is missing

I think this is asking about the same topic as #6179?

Closing as duplicate of #6179. Please let us know if what you're looking for still works on https://wiki.developer.mozilla.org? (We recently changed MDN's frontend; the `wiki.*` site is still running the old frontend code.)

**Closed by callahad** 2019-12-09 17:34 UTC
