### ISSUE TITLE
/en-US/docs/Mozilla/Add-ons/WebExtensions

### ISSUE THREAD

**Issue by HollyHop** [mdn/kuma#6716] opened 2020-03-22 03:34 UTC
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
  
At the very bottom of **all** the MDN WebDocs web pages along the path for [Browser Extensions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions) (at least),  the sign up for the newsletter has format issues for Firefox 74 on macOS 10.12.6.  The email input field and 'Sign up now' button span the entire width of the web page! This issue appears between the "Last Modified" date and the top of the footer.

Paths of docs with issue:  ~/en-US/docs/Mozilla/Add-ons/WebExtensions/....
Example: [https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions)

The issue also is probably elsewhere in WebDocs.  I'd fix it myself if I was not a brand-newbie.

**Comment by chrisdavidmills** [comment] 2020-03-23 11:34
@schalkneethling , I'm guessing this has already been reported, but the styling of the newsletter signup form at the bottom of MDN pages (The "Learn the best of web development" section; see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions for an example) has gone wrong - the form stretches across the full width of the page.

**Comment by schalkneethling** [comment] 2020-03-23 14:21
> @schalkneethling , I'm guessing this has already been reported, but the styling of the newsletter signup form at the bottom of MDN pages (The "Learn the best of web development" section; see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions for an example) has gone wrong - the form stretches across the full width of the page.

Oh boy! I will look into it. Thanks @chrisdavidmills

**Comment by schalkneethling** [comment] 2020-03-23 14:23
There is some CSS missing there :(

**Comment by schalkneethling** [comment] 2020-03-23 14:50
Thanks for reporting @HollyHop!

Closing as a duplicate of https://github.com/mdn/kuma/issues/6713

**Closed by schalkneethling** 2020-03-23 14:50 UTC
