### ISSUE TITLE
Improve implementation of deleteSubscriptions API - React

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#7286] opened 2020-06-29 11:58 UTC
In https://github.com/mdn/kuma/pull/7276#discussion_r446143535 @Gregoor made a valid point regarding the implementation details of `kuma/javascript/src/payments/api.js`

> I realize these API functions are older than this PR, but I still want to note that I think they should just use good-ol return and throw for success and failure, instead of callbacks. Do with that what you will 🙃

Adding this here to keep track of this. This is open for anyone who wants to pick it up.

**Comment by tobinmori** [comment] 2020-07-20 17:27
Closing: Duplicate of #7302

**Closed by tobinmori** 2020-07-20 17:27 UTC
