### ISSUE TITLE
"Edit in wiki" link does not work if Firefox "Do Not Track" signal is enabled

### ISSUE THREAD

**Issue by annevk** [mdn/kuma#6758] opened 2020-03-27 10:38 UTC
**Summary**
_What is the problem?_

Cannot click "Edit in wiki" link directly. cmd+click or right click works.

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Use Firefox.
1. Visit about:preferences#privacy
1. Enable "Do Not Track"
1. Visit https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/Planned_changes.
1. Ensure you're logged in.
1. Click "Edit in wiki"

**Actual behavior**
_What actually happened?_

Nothing.

**Expected behavior**
_What did you expect to happen?_

Go the wiki.

**Additional context**
_Is there anything else we should know?_

The amount of code executed for this click seems over the top.

**Comment by atopal** [comment] 2020-03-30 15:51
Weird, I can't reproduce this. I have DNT enabled, but clicking "edit in wiki" opens the wiki as expected. What version of Firefox are you using Anne?

**Comment by annevk** [comment] 2020-03-30 16:01
Firefox Nightly (76.0a1 (2020-03-30) (64-bit), macOS).

**Comment by schalkneethling** [comment] 2020-03-30 16:48
I can reproduce.

- Open Nightly and enable DNT
- Open https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/Planned_changes
- Click "Edit in Wiki"

It does not work

- Turn off DNT
- Refresh page
- Click link
- It Works!

Something in Nightly's DNT does not like us linking to a subdomain. Perhaps auth/ cookie related?

**Comment by annevk** [comment] 2020-03-30 16:52
It might be anti-tracking related. Something goes wrong in the Google Analytics code.

**Comment by englehardt** [comment] 2020-03-30 22:52
I don't think this is anti-tracking related. I can reproduce when I disable all tracking protection in Nightly and only enable DNT.

**Comment by schalkneethling** [comment] 2020-03-31 08:42
This definitely has something to do with the fact that the link point at a subdomain. 

I can replicate it locally as well and so, the URL of the page would, for example, be `http://localhost.org:8000/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/Planned_changes` and the "Edit in wiki" link would point to `http://wiki.localhost.org:8000/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/Planned_changes`

In this scenario with DNT set to "Always" the link does not work. If I change the URL of the link to ``http://localhost.org:8000/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/Planned_changes` (without the `wiki.`), it works just fine.

I cannot replicate this in any other browser(version)

**Comment by annevk** [comment] 2020-03-31 08:49
@schalkneethling yeah, there's some (React) code that only gets invoked if the link points to a different domain, that then invokes Google Analytics. I'm somewhat surprised we use Google Analytics to begin with.

**Comment by peterbe** [comment] 2020-03-31 17:08
Yeah, that has to be it. Steps to reproduce. 
Go to https://developer.mozilla.org/en-US/docs/Web/HTML
and type the following into the Web Console
```
var a = document.createElement('a')
a.textContent = "CLICK ON ME"
document.body.appendChild(a)
```

The link is numb. It doesn't do anything when you click it.

**Comment by peterbe** [comment] 2020-03-31 17:28
The flaw must be somewhere in this code: https://github.com/mdn/kuma/blob/f84e2175efe65e15a115ce32ca77f60d6c85ef36/kuma/static/js/analytics.js#L37-L61

And when I go to https://developer.mozilla.org/en-US/docs/Web/HTML I can't click the "Edit in wiki" button. But if I ⌘-click it, it does load fine. That's because that triggers `newTab` to be true so it runs this part: https://github.com/mdn/kuma/blob/f84e2175efe65e15a115ce32ca77f60d6c85ef36/kuma/static/js/analytics.js#L245 which basically means it's not trying to prevent the click to execute the Google Analytics trackEvent before proceeding. 

Actually, I can now reproduce this behavior locally. In my FirefoxNightly, if I disabled tracking protection for `localhost.org:8000` my buttons are now as numb as they are on production:
<img width="477" alt="Screen Shot 2020-03-31 at 1 27 45 PM" src="https://user-images.githubusercontent.com/26739/78056664-80e20f80-7353-11ea-9db4-5164e0571895.png">

**Comment by peterbe** [comment] 2020-03-31 17:36
@atopal @tobinmori I've elevated this to a P1. Yes, more people are using Chrome and but there are still huge number of people who use Firefox (independent of version I think) that have tracking protection disabled for developer.mozilla.org

It's not just the "Edit in wiki" button. It's *any* link that is an outbound link with a different domain. For example, if I go to https://developer.mozilla.org/en-US/ all the Hacks posts listed, they're all unclickable. I can ⌘-click them but not single-click. This is embarrassing and should be fixed.

**Closed** 2020-04-02 14:57 UTC
Labels: p1
