### ISSUE TITLE
Profile Page Cleanup

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6316] opened 2020-01-08 17:35 UTC

**Comment by peterbe** [comment] 2020-01-08 17:47
Should we really bother filing this? Especially as an epic. 

What's coming is that we're going to do away with profiles anyway. (No more "This is my LinkedIn URL") It definitely seems like there's a strong concensus based on the early sketches that Mustafa is pondering. In those sketches, there'll be a Settings page. Only. And sub-pages within there (e.g. Subscriptions, Newsletter, Delete Account, Browser Sets). And it'll sit on the read-only site and you won't have a public URL that you can share at all. (e.g. instead of `/en-US/profiles/peterbe` it'll just be `/en-US/settings`)

What we *could* do is two other smaller individual "micro projects":

1. Remove all the social networking URLs stuff and remove the ability to pick Tags you're interested in, from the the Wiki profile page. 
2. Move the "Edit profile" and "View profile" from the Wiki to the read-only site. Essentially render those existing jinja templates with the different base jinja template.

**Comment by schalkneethling** [comment] 2020-01-09 04:20
@peterbe Yup, yup :) Also to be clear, this relates specifically to the Edit Profile page but, some of the changes will undoubtedly affect the view profile page as well.

I thought it made sense for us to create an epic and I can then go in and create a few smaller issues that we can connect to this. The overall priority of the Epic will not be super high, but some of the individual issues might be seen as either 1) high enough priority to justify work or, 2) something that is well worth the time when someone has some available free cycles.

Hope that clears it up a bit.

**Comment by atopal** [comment] 2020-01-09 12:13
I'm not a fan of a low priority epic that we add things to from time to time unrelated to any user story. We have done that in the past and it's a recipe for scope creep. Having an epic is fine, but not an empty one. It should state clearly what the problem is, why we are addressing it and for whom and at what point we'll consider it done.

**Comment by schalkneethling** [comment] 2020-01-09 13:41
> I'm not a fan of a low priority epic that we add things to from time to time unrelated to any user story. We have done that in the past and it's a recipe for scope creep. Having an epic is fine, but not an empty one. It should state clearly what the problem is, why we are addressing it and for whom and at what point we'll consider it done.

Agreed, I am in the process of adding all of that.

**Comment by tobinmori** [comment] 2020-01-09 13:59
Yes, this was a placeholder for stories by @schalkneethling, not intended to be an empty Epic. That would be weird!

**Comment by schalkneethling** [comment] 2020-05-27 16:19
Closing this one and a few others as we are now implementing the new account experience which is tracked via different issues.

**Closed by schalkneethling** 2020-05-27 16:19 UTC
Labels: Epic
