### ISSUE TITLE
The Browser compatibility table shows strange when showing more than one details

### ISSUE THREAD

**Issue by 14725** [mdn/kuma#7337] opened 2020-07-12 12:46 UTC
**Summary**
_What is the problem?_
The Browser compatibility table shows strange when showing more than one details.

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

As the attached video:
1. Open a page with a "Browser compatibility" and scroll to it.
2. Click one arrow,
3. then click another one,
...

**Actual behavior**
_What actually happened?_
There shows 2 panel, but one is empty.
We have to click 2 times to close the 'empty' panel.

**Expected behavior**
_What did you expect to happen?_
For 1. ,there may be only 1 panel or 2 panel with something showing, thus 2. should not happen at all.

**Additional context**
_Is there anything else we should know?_

I came from [ https://bugzilla.mozilla.org/show_bug.cgi?id=1650766](https://bugzilla.mozilla.org/show_bug.cgi?id=1650766), there is a video mentioned above.

**Comment by tobinmori** [comment] 2020-07-13 16:18
Duplicate of #6968

**Closed** 2020-07-13 16:20 UTC
