### ISSUE TITLE
内部服务器错误(Internal Server Error)

### ISSUE THREAD

**Issue by VemboLiu** [mdn/kuma#6673] opened 2020-03-12 04:15 UTC
**Summary**
_What is the problem?_

Each time I try to submit the translation,It shows error in specific page--`/docs/Learn/CSS/Building_blocks/Selectors`

The problem never happend when I try to submit in other pages.
**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. try to translate the page /docs/Learn/CSS/Building_blocks/Selectors into zh-CN
2. which would open page https://wiki.developer.mozilla.org/zh-CN/docs/Learn/CSS/Building_blocks/Selectors$translate?tolocale=zh-CN
3. submit and it jumped to the "内部服务器错误"page.(Internal Server Error)

**Actual behavior**
_What actually happened?_
内部服务器错误Internal Server Error

**Expected behavior**
_What did you expect to happen?_
It should jumped to the page revised.

**Additional context**
_Is there anything else we should know?_
None,thanks.

**Comment by VemboLiu** [comment] 2020-03-12 07:18
also as _Internal Server Error_ in English

**Comment by atopal** [comment] 2020-03-16 15:13
I can reproduce on staging.

**Comment by tobinmori** [comment] 2020-03-16 16:08
Timebox investigate the cause.

**Comment by peterbe** [comment] 2020-03-17 18:21
The explanation is that https://wiki.developer.mozilla.org/zh-CN/docs/Learn/CSS/Building_blocks/Selectors is deleted. Technically, soft-deleted. 
```
>>> Document.deleted_objects.filter(slug='Learn/CSS/Building_blocks/Selectors', locale='zh-CN')
<QuerySet [<Document: /zh-CN/docs/Learn/CSS/Building_blocks/Selectors (CSS selectors)>]>
>>>
```

If you for some reason is reading https://developer.mozilla.org/zh-CN/docs/Learn/CSS/Building_blocks/Selectors it actually falls back on the en-US text. 

You can see that it was deleted in September 2019 (by SphinxKnight)
https://wiki.developer.mozilla.org/zh-CN/docs/Learn/CSS/Building_blocks/Selectors

So, @VemboLiu Can you share how you even got to that?

**Comment by peterbe** [comment] 2020-03-17 18:26
Actually, I think I know what's going on. 
You're on https://developer.mozilla.org/zh-CN/docs/Learn/CSS/Building_blocks/Selectors and see all the English text and you decide you want to translate it to Chinese (Simplified?). You click the language drop-down menu and select the bottom option (添加翻译) ("Add translation")
That takes you to https://wiki.developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors$locales and there you click on "中文 (简体) (zh-CN)"  and from there it takes you to https://wiki.developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors$translate?tolocale=zh-CN and you make your edits and press the "Publish" button. And that's when the error happens. 

So @VemboLiu you're not doing anything wrong. It's our fault! Sorry. 
What should happen is that before it creates this new translation it needs to notice if there was a previous soft-delete of it and just completely delete it (hard delete).

**Comment by VemboLiu** [comment] 2020-03-18 12:39
@peterbe Yes,just as your discription.Glad that it would help.So now I think that about this page ,we can only translate it until the problem fixed,right? Thanks for your generous help !

**Comment by peterbe** [comment] 2020-03-18 12:46
> @peterbe Yes,just as your discription.Glad that it would help.So now I think that about this page ,we can only translate it until the problem fixed,right? Thanks for your generous help !

As soon as the [pull request](https://github.com/mdn/kuma/pull/6692) has been reviewed and merged, it'll be a couple of days until it goes into production. We'll probably soon close this issue a bit before the next production build. 

By the way; hi! How are you? Are you doing a lot of translations from English to Chinese (Simplified?)

**Comment by VemboLiu** [comment] 2020-03-19 03:00
> @peterbe By the way; hi! How are you? Are you doing a lot of translations from English to Chinese (Simplified?)

Yes I'm trying to translate and fix errors in former translation in my spare time.

**Comment by peterbe** [comment] 2020-03-20 19:52
Sentry issue: [MDN-PROD-14B](https://sentry.prod.mozaws.net/operations/mdn-prod/issues/7599932/)

**Closed** 2020-03-26 19:36 UTC
Labels: p2

**Comment by peterbe** [comment] 2020-03-26 19:43
@VemboLiu Hey, We've fixed the problem and that closes this issue but it hasn't roll out on https://developer.mozilla.org yet. It will soon. Actually in a matter of hours.
