### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by Tannyr** [mdn/kuma#7558] opened 2020-10-13 21:11 UTC
**Summary**
_What is the problem?_
Demos fail to work.

Here: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas
"Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data."

This is occurring on Chrome.

**Comment by AprilMorone** [comment] 2020-10-14 13:21
There also is an issue with responsive design of this linked web page in
Portrait mode in both Chrome and Firefox Focus browsers on the Samsung
Galaxy S10e phone (that web page linked isn't responsive of search icon).

**Comment by AprilMorone** [comment] 2020-10-14 13:24
But, it is responsive on Samsung Galaxy S10+ (a bigger phone). I tested it
each phone.

**Comment by AprilMorone** [comment] 2020-10-14 13:55
(I noticed that issue when trying to reproduce the original issue mentioned
in this thread)

**Comment by escattone** [comment] 2020-10-19 16:44
@Tannyr Thanks for reporting this issue. We will look into it, and post what we find here in this issue.

**Comment by escattone** [comment] 2020-10-19 16:46
@AprilMorone Could you please file a separate issue for the responsive design issue you found, and include images of the problem if you can?

**Comment by AprilMorone** [comment] 2020-10-20 14:27
Yes, I will, tomorrow, if possible (recuperating from knee surgery at the
moment). I will try to remember to do so, then.

**Comment by escattone** [comment] 2020-10-20 15:22
@AprilMorone Thank you, and wishing you a speedy recovery!

**Comment by AprilMorone** [comment] 2020-10-21 22:01
You're welcome.😊 Thank you.

**Comment by escattone** [comment] 2020-10-22 02:28
@Tannyr Thanks again for notifying us of this. I started looking into it a bit today, and so far I'm puzzled why we're not responding with the proper CORS headers when it seems that we should based on what we have configured.

**Comment by AprilMorone** [comment] 2020-10-22 10:39
I am behind because I am still recuperating from surgery. But, I will
attempt to get this done within two weeks.

**Comment by AprilMorone** [comment] 2020-10-22 10:42
(about the Responsive Design issue)

**Comment by escattone** [comment] 2020-10-22 22:34
For the record, the problem here had two causes:
1. Our media CDN (we have one for both the stage and prod environments), was not caching on the `Origin` header as well as not forwarding it to its S3 origin. Its S3 origin was already configured to provide the proper CORS headers in its response (e.g., `access-control-allow-origin`), but would never provide them because it never received an `Origin` header.
1. The live-examples embedded in the document that were experiencing CORS security errors had to be modified to set the `crossOrigin` attribute on the image being downloaded. For example,
    ```js
    img.crossOrigin = 'anonymous';
    ```

I fixed the first cause today, and the second cause has to be fixed on each document where it exists. While I was working on the first cause, an MDN user fixed the second for https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas, but there may be other documents that exhibit this problem as well. I'll add a separate comment if I find any others.

cc @chrisdavidmills @peterbe

**Comment by escattone** [comment] 2020-10-22 22:51
After some searching, it seems https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas and its translations are the only documents with this problem.

**Comment by chrisdavidmills** [comment] 2020-10-23 09:39
Thanks @ryan ! We have a couple of different issues over on the sprints repo about this one. I am going to close this one as a dupe of https://github.com/mdn/sprints/issues/1127, which is where it looks like we are implementing a final solution for this (putting the examples on GitHub and embedding them from there, so all of the example files will be in the same origin).

**Closed by chrisdavidmills** 2020-10-23 09:39 UTC
