### ISSUE TITLE
UnicodeEncodeError in Admin console

### ISSUE THREAD

**Issue by escattone** [mdn/kuma#6001] opened 2019-10-16 22:27 UTC
**Summary**
We get an ISE (UnicodeEncodeError) when hitting https://developer.mozilla.org/admin/wiki/revisionakismetsubmission/ (as well as other admin endpoints like https://developer.mozilla.org/admin/wiki/bcsignal/1766/change/)

**Steps To Reproduce (STR)**
Visit https://developer.mozilla.org/admin/wiki/revisionakismetsubmission/ or https://developer.mozilla.org/admin/wiki/bcsignal/1766/change/

**Actual behavior**
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/3743693/66963768-5c0a1200-f029-11e9-9b6d-7c66086aeab0.png">

**Expected behavior**
Successful page view.

**Comment by peterbe** [comment] 2019-10-18 15:46
For what it's worth I can't reproduce this. I opened a browser and submitted a couple where I wrote text in non-ascii, like "På svenskä" and for Chinese I just copy and pasted some blobs of text from https://developer.mozilla.org/zh-CN/
They worked locally. 
I wonder if there's a way to inject really weird Window unicode characters or something. Sigh. It's 2019 and we have to deal with this!

**Comment by peterbe** [comment] 2019-10-18 16:23
Here's a something:

```
>>> b=BCSignal.objects.get(pk=1766)
>>> b
<BCSignal: BC Signal: Web/JavaScript/Reference/Opérateurs/Opérateurs_de_comparaison>
>>> b.document
<Document: /fr/docs/Web/JavaScript/Reference/Op%C3%A9rateurs/Op%C3%A9rateurs_de_comparaison (Opérateurs de comparaison)>
>>> b.browsers
u''
>>> b.feature
u''
>>> b.explanation
u''
>>> b.supporting_material
u''
```

In other words, it appears someone has managed to submit with all fields left empty.

**Comment by peterbe** [comment] 2019-10-18 16:26
I can reproduce the `UnicodeEncodeError` locally.

**Comment by peterbe** [comment] 2019-10-18 17:22
Some documents simply can't be printed:

```
>>> b.document.title
u'Op\xe9rateurs de comparaison'
>>> b.document.slug
u'Web/JavaScript/Reference/Op\xe9rateurs/Op\xe9rateurs_de_comparaison'
>>> str(b.document)
'/fr/docs/Web/JavaScript/Reference/Op%C3%A9rateurs/Op%C3%A9rateurs_de_comparaison (Op\xc3\xa9rateurs de comparaison)'
>>> print b
Traceback (most recent call last):
  File "<console>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 38: ordinal not in range(128)
```

It's probably related to the fact that the model has a `__str__` but it tries to return a unicode which is forced to ascii and that breaks because it doesn't get a chance to supply the encoding.

**Comment by peterbe** [comment] 2019-10-18 17:34
Ugh! I give up for now. I tried a million different combinations to try to figure out how to NOT trigger this stringifcation of a document whose slug contains non-ascii characters. 
Nothing worked. You can't simply avoid the `document` field because it still cause the error. 

Perhaps best to simply wait till we've upgraded to Python 3.

**Comment by tobinmori** [comment] 2019-10-21 16:29
Will wait on a fix for this, after python3 is pushed.

**Comment by peterbe** [comment] 2019-10-23 16:10
I'm pretty confident this will be resolved when switching to Python 3.
Here I'm on the [python3 branch](https://github.com/mdn/kuma/pull/5518):
<img width="1029" alt="Screen Shot 2019-10-23 at 12 08 48 PM" src="https://user-images.githubusercontent.com/26739/67412804-f7513900-f58d-11e9-8ccb-36cf13df4005.png">

It didn't work before.

**Comment by peterbe** [comment] 2019-11-15 19:16
This got solved with the Python 3 upgrade. All those URLs work now.

**Closed by peterbe** 2019-11-15 19:16 UTC
Labels: p5
