### ISSUE TITLE
Message about translation status differ in wiki vs read-only

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6308] opened 2020-01-07 13:20 UTC
**Summary**
Compare https://developer.mozilla.org/de/docs/Web/HTML/Element/form and https://wiki.developer.mozilla.org/de/docs/Web/HTML/Element/form

On the read-only, it says:

*"You are reading the English version of this content because there is no translation for this locale yet. Help us translate this article!"*

But clearly the text is in German. 

On the wiki it says:

*"This translation is incomplete. Please help translate this article from English."*

which I can believe to be accurate.

**Comment by Gregoor** [comment] 2020-01-08 09:23
Indeed, #6271 should fix it and I believe this issue to be a duplicate of #6251

**Comment by peterbe** [comment] 2020-01-08 17:11
Let's hope! I put in an extra "Fixes ..." on https://github.com/mdn/kuma/pull/6271

**Closed** 2020-01-13 15:10 UTC
Labels: status: needs triage
