### ISSUE TITLE
Strict MIME checking broke the demos style

### ISSUE THREAD

**Issue by NGrossman** [mdn/kuma#6115] opened 2019-10-16 08:58 UTC
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Error loading https://developer.mozilla.org/en-US/docs/Web/CSS/resize et al.:

"Refused to apply style from 'https://mdn.mozillademos.org/static/build/styles/samples.37902ba3b7fe.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled."

**Comment by chrisdavidmills** [comment] 2019-11-14 13:35
This si the only page I've seen that does this, but I am worried that more live ssamples will be affected. It is indicating that some styling is not being applied to the demo inside the IFrame because of this, so it should at least be investigated.

**Comment by atopal** [comment] 2019-11-14 13:37
Marking as a P2 for the next sprint

**Comment by peterbe** [comment] 2019-11-25 20:22
Generally the problem isn't with MIME types. [The iframe](https://mdn.mozillademos.org/en-US/docs/Web/CSS/resize$samples/Using_resize_with_arbitrary_elements?revision=1528269) uses 
```
<link href="/static/build/styles/samples.37902ba3b7fe.css" rel="stylesheet" type="text/css" />
```
which means that the browser is GET'ing `https://mdn.mozillademos.org/static/build/styles/samples.37902ba3b7fe.css` but that URL causes a 404. And it also contains this HTTP response header:
```
x-cache: Error from cloudfront
```
For the record, `https://developer.mozilla.org/static/build/styles/samples.37902ba3b7fe.css` works and I've double-checked that that file really does exist inside the docker container in production.

**Comment by peterbe** [comment] 2019-11-26 16:04
I'm understanding it a bit more now. This is a DevOps problem. Not a "traditional" web dev problem. It's about how we do AWS and stuff in Kuma. 

First of all, the `x-cache: Error from cloudfront` means when you use CloudFront and the origin yields a 404. For example:
```
▶ curl -I https://developer.mozilla.org/static/build/styles/home.67907b377f79.css
HTTP/2 200
...
x-cache: Hit from cloudfront
...

▶ curl -I https://developer.mozilla.org/static/build/styles/home.doesnotexist.css
HTTP/2 404
...
x-cache: Error from cloudfront
...
```

What happens is not that our Django code fails to find the file. The file `/static/build/styles/samples.37902ba3b7fe.css` totally exists on disk. 
However, the way we use Whitenoise is such that if the host you use is not `settings.ATTACHMENT_ORIGIN` or `settings.ATTACHMENT_HOST` our Whitenoise override  basically says to Whitenoise to not bother and Whitenoise thinks this means the file doesn't exist. 

The lines responsible for this is here: https://github.com/mdn/kuma/blob/5a9fb57aa304ed0724e7fd1cff89b4540ba0f0de/kuma/core/middleware.py#L343-L344

I think that `return None` should be replaced with `return HttpResponseForbidden()` to avoid this kind of misleading debugging. I'll make a PR for that. 

Now let's talk about domains, origins, and attachments...

**Comment by peterbe** [comment] 2019-11-26 16:37
When `GET` a URL like `/static/build/styles/samples.37902ba3b7fe.css` in an iframe, on a page like https://developer.mozilla.org/en-US/docs/Web/CSS/resize it ultimately means that the iframe runs within `mdn.mozillademos.org`. So the URL we're struggling with is https://mdn.mozillademos.org/static/build/styles/samples.37902ba3b7fe.css

In production, `mdn.mozillademos.org` is actually the value of `settings.ATTACHMENT_HOST` which according to `RestrictedWhiteNoiseMiddleware` is "untrusted". 

In other words, we're not allowing Whitenoise to serve any static files unless the host is `developer.mozilla.org` (our main CloudFront domain) or `prod.mdn.mozit.cloud` (our CloudFront origin domain). 
So, we're happy to serve things like `/en-US/docs/Web/CSS/resize$samples/...` under `mdn.mozillademos.org` but not things like `/static/...`. 

I can think of hacks to do to remedy this now, but nothing that I'm comfortable with in a quick fix. The reasons for these restrictions and stuff is related to security which is a minefield in the case of interactive examples. 

The problem is the same with [`wiki.developer.mozilla.org` too](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/resize) by the way. 

I think I'd rather leverage @escattone 's opinions on this since he's most likely more aware of the implications.

**Comment by tobinmori** [comment] 2019-11-26 19:26
cool, thanks for digging deep into that @peterbe. 

so maybe it's as easy as adding `mdn.mozillademos.org` `static` to whitenoise on prod?

in any case, we can wait for @escattone on this one since he probably understands this best.

**Comment by escattone** [comment] 2019-12-02 21:55
@peterbe and I discussed this verbally in our video meeting earlier today, so I thought I'd summarize that here for the record.

I think this issue is an unintended consequence of moving from an absolute value to the default relative value for the `STATIC_URL` setting (see https://github.com/mdn/infra/pull/276). @peterbe and I couldn't see any reason to not serve static files, which we completely control, to the attachment domain.

**Closed** 2019-12-07 00:26 UTC
Labels: p1
