### ISSUE TITLE
Error pages have the wrong header

### ISSUE THREAD

**Issue by escattone** [mdn/kuma#5623] opened 2019-08-05 17:49 UTC
Currently, error pages on `developer.mozilla.org` have a header, for example:

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/3743693/62484406-f965e180-b76e-11e9-8f4f-fcd97ffcf18e.png">

but error pages on the `beta.developer.mozilla.org` do not, for example:

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/3743693/62484476-1c909100-b76f-11e9-93ac-7e4b1aebcd55.png">

**Comment by escattone** [comment] 2019-08-05 19:12
https://bugzilla.mozilla.org/show_bug.cgi?id=1571514

**Comment by ankiiitraj** [comment] 2019-08-09 10:53
I wanted to get stated with contributing with this Bug. Can you Help me in getting started.

**Comment by schalkneethling** [comment] 2019-08-16 06:07
Hey @ankiiitraj - Thank you for your interest in contributing to MDN o/\o

This issue is a bit more involved/nuanced than it sounds but, here is a good first bug you might be interested in - https://github.com/mozilla/kuma/issues/5647

If you are, please let me know in the issue, and I would be happy to mentor you through the process.

**Comment by ExE-Boss** [comment] 2019-08-19 15:39
I can’t reproduce this anymore.

Did this get fixed?

**Comment by peterbe** [comment] 2019-08-19 16:20
> Did this get fixed?

Nope. Not yet.

**Comment by ExE-Boss** [comment] 2019-08-20 14:02
Have beta error pages been disabled?

Because I get the jinja2‑based error page, even on the beta endpoint:

![Kuma Issue-5623](https://user-images.githubusercontent.com/3889017/63353896-c4a77c00-c363-11e9-8e8e-76d62338957f.png)

**Comment by peterbe** [comment] 2019-08-20 15:52
Weird. It used to be entirely without a header. Now it's the Wiki header. Odd. Can you figure out what's going on?

**Comment by ExE-Boss** [comment] 2019-08-20 17:29
Well, I installed the [React Dev Tools](https://addons.mozilla.org/firefox/addon/react-devtools/), and it says that **React** isn’t running on the page.

**Comment by schalkneethling** [comment] 2019-08-21 02:47
> Weird. It used to be entirely without a header. Now it's the Wiki header. Odd. Can you figure out what's going on?

Perhaps the [PR from Ryan](https://github.com/mozilla/kuma/pull/5614) resolved that somehow?

**Comment by ExE-Boss** [comment] 2019-08-22 17:30
Well, the header should be changed to the new React‑based header.

**Comment by ExE-Boss** [comment] 2019-08-22 21:33
@schalkneethling
Actually, the commit that added the wiki header was https://github.com/mozilla/kuma/commit/30b957283ed164a4dd3c26e7766ee1cd731c8700#diff-4deb7373bef351eea78be191276dffa1.

**Comment by tobinmori** [comment] 2019-10-12 12:37
the header appears on the beta site, so closing this.

**Comment by ExE-Boss** [comment] 2019-10-12 12:41
The header that appears on the beta error pages is the wiki header, not the react header, so this should maybe be converted to changing the header to be the react header.

**Comment by peterbe** [comment] 2019-11-25 17:11
@ExE-Boss is right. It's still not fixed. See https://github.com/mdn/kuma/issues/6153

**Comment by peterbe** [comment] 2020-04-20 14:04
@atopal @tobinmori I think we should re-prioritize this one since it's one of many potential wiki related issues that block Yari. If we still rely on the Wiki rendering, we won't be able to replace it with Yari.

**Comment by atopal** [comment] 2020-04-21 12:15
Sure Peter, but I guess we'll take a comprehensive approach to remove the wiki headers, right? Not just for the error pages.

**Comment by peterbe** [comment] 2020-04-21 12:20
> Sure Peter, but I guess we'll take a comprehensive approach to remove the wiki headers, right? Not just for the error pages.

Technically, we won't "remove the wiki HEADERS". We'll remove the wiki. So, when that day comes you don't want to also have to worry about porting the `404.html` and `500.html` templates as well.

**Comment by bensternthal** [comment] 2021-08-20 21:49
Closing as beta.developer.mozilla.org is no more!

**Closed by bensternthal** 2021-08-20 21:49 UTC
Labels: p5
